# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScannerExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScannerExampleApp
  pod 'scanCocoaPod', :path => "../scanCocoaPod/"

  target 'ScannerExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScannerExampleAppUITests' do
    # Pods for testing
  end

end
